from collections.abc import Iterable, Iterator
from typing import cast

import openai
from openai.types.chat import ChatCompletionMessageParam

from backends.base_backend import BaseBackend


class LMStudioBackend(BaseBackend):
    """
    Connects to a locally running LM Studio server.
    LM Studio exposes an OpenAI-compatible API at http://localhost:1234/v1
    No API key is required for local use.
    """

    def __init__(
        self,
        base_url: str = "http://localhost:1234/v1",
        model: str = "local-model",
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ):
        self.client = openai.OpenAI(
            base_url=base_url,
            api_key="lm-studio",   # required by client lib but not validated
        )
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens

    def chat(self, messages: list[dict]) -> str:
        """Send a message list and return the assistant reply as a string."""
        try:
            typed_messages = cast(
                Iterable[ChatCompletionMessageParam], messages
            )
            response = self.client.chat.completions.create(
                model=self.model,
                messages=typed_messages,
                temperature=self.temperature,
                max_tokens=self.max_tokens,
            )
            content = response.choices[0].message.content
            if content is None:
                raise ValueError("LM Studio returned an empty assistant response")
            return content
        except Exception as e:
            print(f"Error in chat: {e}")
            raise

    def stream(self, messages: list[dict]) -> Iterator[str]:
        """Yield tokens as they are generated by the model."""
        try:
            typed_messages = cast(
                Iterable[ChatCompletionMessageParam], messages
            )
            stream = self.client.chat.completions.create(
                model=self.model,
                messages=typed_messages,
                temperature=self.temperature,
                max_tokens=self.max_tokens,
                stream=True,
            )
            for chunk in stream:
                delta = chunk.choices[0].delta
                if delta.content:
                    yield delta.content
        except Exception as e:
            print(f"Error in stream: {e}")
            raise

    def list_models(self) -> list[str]:
        """Return model IDs currently loaded in LM Studio."""
        try:
            models = self.client.models.list()
            return [m.id for m in models.data]
        except Exception as e:
            print(f"Error in list_models: {e}")
            raise

    def health_check(self) -> bool:
        """Return True if the LM Studio server is reachable."""
        try:
            self.list_models()
            return True
        except Exception:
            return False